name: Library build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        yarn
        yarn build

    - name: prepare the package
    run: mkdir out && mv package.json out && mv dist out && mv README.md out && mv LICENSE out && mv docs out
    uses: s0/git-publish-subdir-action@production
    if: ${{ github.ref == 'refs/heads/main'}}
    env:
      REPO: self
      BRANCH: production
      FOLDER: out
      GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      MESSAGE: "Build: ({sha}) {msg}"
