name: Libruary build

on:
  push:
    branches:
      - "main"
    
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      name: Build & Push
      steps:
        - name: git-checkout
        uses: actions/checkout@v2

        - name: setup node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 18.16.0

        - name: install dependencies
        run: yarn

        - name: build
        run: yarn build

        - name: prepare the package
        run: mkdir out && mv package.json out && mv dist out && mv README.md out && mv LICENSE out && mv docs out
        uses: s0/git-publish-subdir-action@production
        if: ${{ github.ref == 'refs/heads/main'}}
        env:
          REPO: self
          BRANCH: production
          FOLDER: out
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          MESSAGE: "Build: ({sha}) {msg}"
